### PR TITLE
Update DNSScavengingForPrimaryDNSServer.ps1

### PR DESCRIPTION
**Pull request by JasonCook599**
Change DNS last scavenge time to be less than seven days _from now_, instead of more than seven days _ago_. Test current fails if scavenging occurred too recently.

### CODE REVIEW

**Comment by PrzemyslawKlys** [comment]
(Get-Date).AddDays(7) = 16th of September. This is the future. Everything will be less than that?

**Comment by PrzemyslawKlys** [comment]
I think, fix for this would be changing LT to GT and leaving it as is. What do you think?

**Comment by JasonCook599** [comment]
Both will work identically and I don't have a strong opinion either way. Personally, I find it easier to read/understand "add seven" than "add negative seven".

**Comment by PrzemyslawKlys** [comment]
Are you sure? 

(Get-Date).AddDays(7) = Future date
Any scavenging time - 5 days old, 500 days old will be Less Than that date. 

(Get-Date).AddDays(-7) = Past Data (-7 days)
We expect scavenging Date to be greater than that. So 1-7 days will work, but not 8.

**Comment by JasonCook599** [comment]
You are correct; it should be greater than. I did not think it through fully.

**Comment by PrzemyslawKlys** [comment]
Thank you, please fix it so I can apply your fix!

**Comment by PrzemyslawKlys** [comment]
Thank you! Really appreciate it!

**Pull request merged**
