### PR TITLE
Fix PowerShell 2.0 detection

### PR DESCRIPTION
**Pull request by Sparticuz**
Trying to compare to a property that isn't returned.

### CODE REVIEW

**Comment by PrzemyslawKlys** [comment]
Sometimes I wonder what I have in my mind when I do commits like this. Thank you

**Comment by Sparticuz** [comment]
....it's ok... i literally crashed my PDC trying to fix this....then i looked at the code, lol. At least i know my recovery steps work.
image

**Comment by Sparticuz** [comment]
@PrzemyslawKlys Still having problems with this one, but don't know how to fix it.

```
PS C:\Users\Administrator> Get-WindowsOptionalFeature -Online -FeatureName MicrosoftWindowsPowerShellV2 | Select-Object -Property DisplayName, Description, RestartRequired, FeatureName, State


DisplayName     : Windows PowerShell 2.0 Engine
Description     : Adds or Removes Windows PowerShell 2.0 Engine
RestartRequired : Possible
FeatureName     : MicrosoftWindowsPowerShellV2
State           : Disabled
```
image

**Comment by PrzemyslawKlys** [comment]
Ye, it's because State is actually Enum. 

image

So within Testimo

image

I need to see whether to fix test or fix internals to support this properly.

**Pull request merged**
