### PR TITLE
Add networks card info #43 and #56 and guest user #88

### PR DESCRIPTION
**Pull request by itpro-tips**
Use guest user instead of guest group #88
Fix some typo
Add network card infos related to loopback #43, DHCP #56 and WindowsFirewall Profile

### CODE REVIEW

**Comment by PrzemyslawKlys** [comment]
I wonder if DHCP vs STATIC is still true. Azure machines for DCs are mostly based on DHCP. If you touch network card it disconnects and requires a reboot.

**Comment by PrzemyslawKlys** [comment]
And I wonder if this could be detected and ignored if anything or just relying on disabling test in such circumstances.

**Comment by itpro-tips** [comment]
Yes you're right, in Azure they are mostly in DHCP.
AFAIK [Azure instance metadata service](https://azure.microsoft.com/en-us/blog/announcing-general-availability-of-azure-instance-metadata-service/) can be used to identify Azure VM but maybe not simple to implement.

**Comment by PrzemyslawKlys** [comment]
I'll turn off checking DHCP by default but will leave the test in there. This way anyone who wants to use it can, but I don't think it's required to use STATIC vs DHCP anymore.

**Pull request merged**
